# Setup
title:        Jackralf's Pages
tagline:      A responsive theme for your project on GitHub Pages
baseurl:      "https://jackralf.github.io"
paginate:     1

# About/contact
author:
  name:       machenfei
  url:        https://jackralf.github.io 

# Gems
gems:
  - jekyll-paginate

#Others
markdown: kramdown