# Setup
title:        Jackralf's Pages
tagline:      
baseurl:      ""
paginate:     10

# About/contact
author:
  name:       machenfei
  url:        https://jackralf.github.io 

# Gems
gems:
  - jekyll-paginate

#Others
markdown: kramdown